7455 - 20-01-16 12:36:32 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196191.006700', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '#NoNeedForAlarmItsJust A test of the Emergency Broadcast System that is on the radio every day with that annoying buzzing sound', 'ts': '1579196191.006700', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:32 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:32 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:32 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:32 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:32 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:32 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:32 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196192.007300', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'Lie upon lie upon lie upon lie!  Typical trump administration strategy to distort the truth.', 'ts': '1579196192.007300', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:33 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:33 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196193.007400', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '#NoNeedForAlarmItsJust A test of the Emergency Broadcast System that is on the radio every day with that annoying buzzing sound', 'ts': '1579196193.007400', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:33 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:33 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196193.007500', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': "@FUNTlMEZ The rest of us who didn't pass the test (that was 100% of the note because he wanted)  got really depress… <https://t.co/4VHSkgkvqk>", 'ts': '1579196193.007500', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:34 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:34 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196194.007600', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'If you support trump just unfollow bro', 'ts': '1579196194.007600', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:35 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:35 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:35 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196195.007700', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@Malinowski Since they want Biden and his son to testify so badly, why don’t we offer them a deal? If Trump, Pence… <https://t.co/Blunk2gF35>', 'ts': '1579196195.007700', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:35 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:35 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:35 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:35 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:35 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:35 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:35 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:35 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196195.007800', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@WilliamNB @theJeremyVine Also test for cocaine', 'ts': '1579196195.007800', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:35 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:35 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196195.007900', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'Live Baby Taste Test Out takes:joy::joy::joy:#livebabytastetest <https://t.co/fSgF4TIdKa>', 'ts': '1579196195.007900', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:35 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:35 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196195.008000', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@SilkyJ3 @VidaurriE @mrbongostx @SenTedCruz You tell people not to testify and to ignore subpoenas and don’t provid… <https://t.co/rZ3rpz2x7H>', 'ts': '1579196195.008000', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:35 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:35 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196195.008100', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@WilliamNB @theJeremyVine Also test for cocaine', 'ts': '1579196195.008100', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:36 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:36 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196196.008200', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': "@Simon_Vessey Threaten to shut down all newspapers, nobody fucking likes journalists, like trump's hatred of the pr… <https://t.co/xgoBOWbht2>", 'ts': '1579196196.008200', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:36 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:36 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:36 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196196.008300', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'Live Baby Taste Test Out takes:joy::joy::joy:#livebabytastetest <https://t.co/fSgF4TIdKa>', 'ts': '1579196196.008300', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:36 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196196.008400', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@BernieSanders *want to stop us* for some reason “hates us” just sound like a trump line...', 'ts': '1579196196.008400', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:36 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:36 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196196.008500', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': "ENFIN ! L'emoji drapeau breton est en test sur Twitter et je soutiens sa création ! Vive l' #EmojiBZH ! #Bretagne", 'ts': '1579196196.008500', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:36 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:36 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196196.008600', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@CBSNews Like trump doesn’t do it every time he signs something shm', 'ts': '1579196196.008600', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:36 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:36 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:36 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196196.008800', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@WorldofKeralis If you want to test the machine. Do a fur mark benchmark test', 'ts': '1579196196.008800', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:36 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:37 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:37 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196197.009000', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': "ENFIN ! L'emoji drapeau breton est en test sur Twitter et je soutiens sa création ! Vive l' #EmojiBZH ! #Bretagne", 'ts': '1579196197.009000', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:37 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:37 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196197.009100', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@hopesolo Hope what do you think about the trump impeachment ?', 'ts': '1579196197.009100', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:37 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:37 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:37 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196197.009300', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'Does Mahomes really "pass" the eye test? :joy:', 'ts': '1579196197.009300', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:38 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:38 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196198.009400', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'Les dejo la lista del test para que lo hagan y vean que tan resilientes son <https://t.co/kN0nqKl17y>', 'ts': '1579196198.009400', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:38 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:38 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196198.009500', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'Les dejo la lista del test para que lo hagan y vean que tan resilientes son <https://t.co/kN0nqKl17y>', 'ts': '1579196198.009500', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:38 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:38 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196198.009600', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@aaminah_97 @sucre_mack I once passed a Liam Payne challenge online even though the test was in Spanish and I had n… <https://t.co/93IWQT2753>', 'ts': '1579196198.009600', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:39 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:39 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196199.009700', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'Snacking on leftovers from today’s test experiment – sweet &amp; spicy salmon\xa0curry…. <https://t.co/MczmTxsDI6> <https://t.co/gQnDcigf7J>', 'ts': '1579196199.009700', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:39 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:39 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196199.009800', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'She’s in perfect step with the trump:rage:', 'ts': '1579196199.009800', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:40 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:40 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196200.009900', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': ":sparkles:Mental illness doesn't excuse you from being an asshole and using it as a trump card when someone calls you out is… <https://t.co/52oEYbJ2QM>", 'ts': '1579196200.009900', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:40 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:40 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196200.010000', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'Here\'s a simple way to evaluate a product team\'s effectiveness: the "cake test." When does your team put a celebrat… <https://t.co/dUlMkSNwQ4>', 'ts': '1579196200.010000', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:41 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:41 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196201.010100', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'Snacking on leftovers from today’s test experiment – sweet &amp; spicy salmon\xa0curry…. <https://t.co/MczmTxsDI6> <https://t.co/gQnDcigf7J>', 'ts': '1579196201.010100', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:41 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:41 - ERROR -  Slack - Unhandled Exception: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:41 - ERROR -  Slack - Unhandled Exception: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:41 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:41 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:41 - ERROR -  Slack - Unhandled Exception: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:41 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:42 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196202.010400', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': ".@LoFredrich tried out @GenoPalate, the DNA test that reveals the best foods to eat based on your genes. Here's wha… <https://t.co/T0zeeKj6av>", 'ts': '1579196202.010400', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:42 - ERROR - Task exception was never retrieved
future: <Task finished coro=<BaseClient._send() done, defined at /home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py:185> exception=SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'ratelimited'}")>
Traceback (most recent call last):
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - ERROR - Task exception was never retrieved
future: <Task finished coro=<BaseClient._send() done, defined at /home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py:185> exception=SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'ratelimited'}")>
Traceback (most recent call last):
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - ERROR - Task exception was never retrieved
future: <Task finished coro=<BaseClient._send() done, defined at /home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py:185> exception=SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'ratelimited'}")>
Traceback (most recent call last):
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - ERROR - Task exception was never retrieved
future: <Task finished coro=<BaseClient._send() done, defined at /home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py:185> exception=SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'ratelimited'}")>
Traceback (most recent call last):
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - ERROR - Task exception was never retrieved
future: <Task finished coro=<BaseClient._send() done, defined at /home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py:185> exception=SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'ratelimited'}")>
Traceback (most recent call last):
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - ERROR - Task exception was never retrieved
future: <Task finished coro=<BaseClient._send() done, defined at /home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py:185> exception=SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'ratelimited'}")>
Traceback (most recent call last):
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - ERROR - Task exception was never retrieved
future: <Task finished coro=<BaseClient._send() done, defined at /home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py:185> exception=SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'ratelimited'}")>
Traceback (most recent call last):
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - ERROR - Task exception was never retrieved
future: <Task finished coro=<BaseClient._send() done, defined at /home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py:185> exception=SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'ratelimited'}")>
Traceback (most recent call last):
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - ERROR - Task exception was never retrieved
future: <Task finished coro=<BaseClient._send() done, defined at /home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py:185> exception=SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'ratelimited'}")>
Traceback (most recent call last):
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:42 - ERROR -  Slack - Unhandled Exception: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
