7455 - 20-01-16 12:36:43 - ERROR -  Slack - Unhandled Exception: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:43 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:43 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:43 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:43 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:43 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196203.010600', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@BernieSanders *want to stop us* for some reason “hates us” just sound like a trump line...', 'ts': '1579196203.010600', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:43 - ERROR - Task exception was never retrieved
future: <Task finished coro=<BaseClient._send() done, defined at /home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py:185> exception=SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'ratelimited'}")>
Traceback (most recent call last):
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:43 - ERROR - Task exception was never retrieved
future: <Task finished coro=<BaseClient._send() done, defined at /home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py:185> exception=SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'ratelimited'}")>
Traceback (most recent call last):
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:43 - ERROR -  Slack - Unhandled Exception: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:43 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:44 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:44 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196204.010800', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': "@Simon_Vessey Threaten to shut down all newspapers, nobody fucking likes journalists, like trump's hatred of the pr… <https://t.co/xgoBOWbht2>", 'ts': '1579196204.010800', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:44 - ERROR -  Slack - Unhandled Exception: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 226, in _send
    return SlackResponse(**{**data, **res}).validate()
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/slack_response.py", line 176, in validate
    raise e.SlackApiError(message=msg, response=self)
slack.errors.SlackApiError: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'}
7455 - 20-01-16 12:36:45 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:45 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196205.011000', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'Live Baby Taste Test Out takes:joy::joy::joy:#livebabytastetest <https://t.co/fSgF4TIdKa>', 'ts': '1579196205.011000', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:46 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:47 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:47 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:47 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7455 - 20-01-16 12:36:47 - DEBUG - Running 1 callbacks for event: 'message'
7455 - 20-01-16 12:36:47 - DEBUG - The Slack RTMClient is shutting down.
7455 - 20-01-16 12:36:47 - INFO - 
--------------------------------------------------
tweets per second: 76.41681431374086
filter count: {'test': 0, 'trump': 0, 'quantum': 0}
total tweets processed: 121
Running: /media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slacktweet.py
stopped on: 0:01:35.006217
--------------------------------------------------

7807 - 20-01-16 12:37:23 - INFO - 
--------------------------------------------------
      Running: /media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slacktweet.py
      started on: 2020-01-16T12:37:23.548937
--------------------------------------------------

7807 - 20-01-16 12:37:23 - DEBUG - Logging into Twitter API
7807 - 20-01-16 12:37:23 - DEBUG - Using selector: EpollSelector
7807 - 20-01-16 12:37:23 - DEBUG - Retrieving websocket info.
7807 - 20-01-16 12:37:23 - DEBUG - Received the following response: {'ok': True, 'url': 'wss://cerberus-xxxx.lb.slack-msgs.com/websocket/1jhCnST7idTJ-Ddstc3O5zeLzeADZpwh3vLgTkhFBJT7tFG1pRdYcpFa-YQB6v8Bbr8BieGBWeJcNTXXivHBb29EsaSbiSkZsP9QLJ-uZnk=', 'team': {'id': 'TCDBX31NH', 'name': 'KenzieBot', 'domain': 'kenziebot'}, 'self': {'id': 'US2URNDB3', 'name': 'bestslackbot'}}
7807 - 20-01-16 12:37:23 - DEBUG - The Websocket connection has been opened.
7807 - 20-01-16 12:37:23 - DEBUG - Running 1 callbacks for event: 'hello'
7807 - 20-01-16 12:37:23 - DEBUG - Using selector: EpollSelector
7807 - 20-01-16 12:37:24 - DEBUG - Received the following response: {'ok': True, 'url': 'https://kenziebot.slack.com/', 'team': 'KenzieBot', 'user': 'bestslackbot', 'team_id': 'TCDBX31NH', 'user_id': 'US2URNDB3', 'bot_id': 'BS0CA5N3U', 'warning': 'superfluous_charset', 'response_metadata': {'warnings': ['superfluous_charset']}}
7807 - 20-01-16 12:37:28 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:28 - INFO - DSD690213
7807 - 20-01-16 12:37:28 - DEBUG - Updating twitter filter keywords
7807 - 20-01-16 12:37:28 - DEBUG - Restarting the twitter stream
7807 - 20-01-16 12:37:28 - DEBUG - Disoconnecting Stream
7807 - 20-01-16 12:37:28 - DEBUG - Starting Twitter Stream
7807 - 20-01-16 12:37:28 - DEBUG - Signing request <PreparedRequest [POST]> using client <Client client_key=JOwzpbrE9uCvoe5ICltEX8Y3P, client_secret=****, resource_owner_key=749662466909483008-0TpJYmNnVchFFZXt8GK42Vog97H9BEr, resource_owner_secret=****, signature_method=HMAC-SHA1, signature_type=AUTH_HEADER, callback_uri=None, rsa_key=None, verifier=None, realm=None, encoding=utf-8, decoding=None, nonce=None, timestamp=None>
7807 - 20-01-16 12:37:28 - DEBUG - Including body in call to sign: True
7807 - 20-01-16 12:37:28 - DEBUG - Collected params: [('delimited', 'length'), ('oauth_nonce', '154379710925695089001579196248'), ('oauth_timestamp', '1579196248'), ('oauth_version', '1.0'), ('oauth_signature_method', 'HMAC-SHA1'), ('oauth_consumer_key', 'JOwzpbrE9uCvoe5ICltEX8Y3P'), ('oauth_token', '749662466909483008-0TpJYmNnVchFFZXt8GK42Vog97H9BEr'), ('track', 'test')]
7807 - 20-01-16 12:37:28 - DEBUG - Normalized params: delimited=length&oauth_consumer_key=JOwzpbrE9uCvoe5ICltEX8Y3P&oauth_nonce=154379710925695089001579196248&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1579196248&oauth_token=749662466909483008-0TpJYmNnVchFFZXt8GK42Vog97H9BEr&oauth_version=1.0&track=test
7807 - 20-01-16 12:37:28 - DEBUG - Normalized URI: https://stream.twitter.com/1.1/statuses/filter.json
7807 - 20-01-16 12:37:28 - DEBUG - Signing: signature base string: POST&https%3A%2F%2Fstream.twitter.com%2F1.1%2Fstatuses%2Ffilter.json&delimited%3Dlength%26oauth_consumer_key%3DJOwzpbrE9uCvoe5ICltEX8Y3P%26oauth_nonce%3D154379710925695089001579196248%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1579196248%26oauth_token%3D749662466909483008-0TpJYmNnVchFFZXt8GK42Vog97H9BEr%26oauth_version%3D1.0%26track%3Dtest
7807 - 20-01-16 12:37:28 - DEBUG - Signature: +HFIeNW01CxTA/PTtYwNUNY7XMY=
7807 - 20-01-16 12:37:28 - DEBUG - Updated url: https://stream.twitter.com/1.1/statuses/filter.json?delimited=length
7807 - 20-01-16 12:37:28 - DEBUG - Updated headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '10', 'Authorization': 'OAuth oauth_nonce="154379710925695089001579196248", oauth_timestamp="1579196248", oauth_version="1.0", oauth_signature_method="HMAC-SHA1", oauth_consumer_key="JOwzpbrE9uCvoe5ICltEX8Y3P", oauth_token="749662466909483008-0TpJYmNnVchFFZXt8GK42Vog97H9BEr", oauth_signature="%2BHFIeNW01CxTA%2FPTtYwNUNY7XMY%3D"'}
7807 - 20-01-16 12:37:28 - DEBUG - Updated body: 'track=test'
7807 - 20-01-16 12:37:28 - DEBUG - Starting new HTTPS connection (1): stream.twitter.com:443
7807 - 20-01-16 12:37:28 - DEBUG - https://stream.twitter.com:443 "POST /1.1/statuses/filter.json?delimited=length HTTP/1.1" 200 None
7807 - 20-01-16 12:37:34 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:34 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196252.011500', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'il est cool le dlc! je vais le test day one,et si il me plait, peut être remplacer villageois?', 'ts': '1579196252.011500', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:36 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:36 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196255.011700', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'We’ve had a test every this week. My brain is fucking frieddddddddd', 'ts': '1579196255.011700', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:37 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:37 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196257.011800', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@albaugh_er @SandayLinda 2/ when I was on #Levothyroxine &amp; did 24 hour test I was told “ abnormally slow heart beat… <https://t.co/DzuPIch0Q0>', 'ts': '1579196257.011800', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:38 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:38 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196258.011900', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'Que bonito cuando hago un test y sale todo verde, viva el Betis me cago en todo ya', 'ts': '1579196258.011900', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:39 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:40 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:40 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196260.012100', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@bhadmus_sultan She probably heard about your exploits and decided to test your abilities... :joy::joy::joy:', 'ts': '1579196260.012100', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:40 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:40 - INFO - DSD690213
7807 - 20-01-16 12:37:40 - DEBUG - Updating twitter filter keywords
7807 - 20-01-16 12:37:40 - DEBUG - Restarting the twitter stream
7807 - 20-01-16 12:37:40 - DEBUG - Disoconnecting Stream
7807 - 20-01-16 12:37:40 - DEBUG - Starting Twitter Stream
7807 - 20-01-16 12:37:40 - DEBUG - Signing request <PreparedRequest [POST]> using client <Client client_key=JOwzpbrE9uCvoe5ICltEX8Y3P, client_secret=****, resource_owner_key=749662466909483008-0TpJYmNnVchFFZXt8GK42Vog97H9BEr, resource_owner_secret=****, signature_method=HMAC-SHA1, signature_type=AUTH_HEADER, callback_uri=None, rsa_key=None, verifier=None, realm=None, encoding=utf-8, decoding=None, nonce=None, timestamp=None>
7807 - 20-01-16 12:37:40 - DEBUG - Including body in call to sign: True
7807 - 20-01-16 12:37:40 - DEBUG - Collected params: [('delimited', 'length'), ('oauth_nonce', '7402288904373510711579196260'), ('oauth_timestamp', '1579196260'), ('oauth_version', '1.0'), ('oauth_signature_method', 'HMAC-SHA1'), ('oauth_consumer_key', 'JOwzpbrE9uCvoe5ICltEX8Y3P'), ('oauth_token', '749662466909483008-0TpJYmNnVchFFZXt8GK42Vog97H9BEr'), ('track', 'test,trump')]
7807 - 20-01-16 12:37:40 - DEBUG - Normalized params: delimited=length&oauth_consumer_key=JOwzpbrE9uCvoe5ICltEX8Y3P&oauth_nonce=7402288904373510711579196260&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1579196260&oauth_token=749662466909483008-0TpJYmNnVchFFZXt8GK42Vog97H9BEr&oauth_version=1.0&track=test%2Ctrump
7807 - 20-01-16 12:37:40 - DEBUG - Normalized URI: https://stream.twitter.com/1.1/statuses/filter.json
7807 - 20-01-16 12:37:40 - DEBUG - Signing: signature base string: POST&https%3A%2F%2Fstream.twitter.com%2F1.1%2Fstatuses%2Ffilter.json&delimited%3Dlength%26oauth_consumer_key%3DJOwzpbrE9uCvoe5ICltEX8Y3P%26oauth_nonce%3D7402288904373510711579196260%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1579196260%26oauth_token%3D749662466909483008-0TpJYmNnVchFFZXt8GK42Vog97H9BEr%26oauth_version%3D1.0%26track%3Dtest%252Ctrump
7807 - 20-01-16 12:37:40 - DEBUG - Signature: PLoXm2ozRJXaexoCwMwKPXRLJ8s=
7807 - 20-01-16 12:37:40 - DEBUG - Updated url: https://stream.twitter.com/1.1/statuses/filter.json?delimited=length
7807 - 20-01-16 12:37:40 - DEBUG - Updated headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Cookie': 'guest_id=v1%3A157919624839482162; personalization_id="v1_UIIWARxt8GcrUyoMV5/h/w=="', 'Content-Length': '18', 'Authorization': 'OAuth oauth_nonce="7402288904373510711579196260", oauth_timestamp="1579196260", oauth_version="1.0", oauth_signature_method="HMAC-SHA1", oauth_consumer_key="JOwzpbrE9uCvoe5ICltEX8Y3P", oauth_token="749662466909483008-0TpJYmNnVchFFZXt8GK42Vog97H9BEr", oauth_signature="PLoXm2ozRJXaexoCwMwKPXRLJ8s%3D"'}
7807 - 20-01-16 12:37:40 - DEBUG - Updated body: 'track=test%2Ctrump'
7807 - 20-01-16 12:37:40 - DEBUG - Starting new HTTPS connection (2): stream.twitter.com:443
7807 - 20-01-16 12:37:40 - DEBUG - https://stream.twitter.com:443 "POST /1.1/statuses/filter.json?delimited=length HTTP/1.1" 200 None
7807 - 20-01-16 12:37:40 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:40 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196260.012300', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@SenMcSallyAZ That doesn’t change the fact that trump is corrupt and has abused his office for political gain. Are… <https://t.co/PkeySU6wQG>', 'ts': '1579196260.012300', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:41 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:41 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196261.012500', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'This is a test ... to see ‘how the population will react’ ... before clamping down on the rest of us ...', 'ts': '1579196261.012500', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:42 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:42 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196262.012600', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'starr said “tell jaylin she can’t talk til she pass a biology test” lmfaooooooo', 'ts': '1579196262.012600', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:42 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:42 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:42 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196262.012800', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'This test is gonna be epic to watch! Max Q In-Flight abort test!! Godspeed, Crew Dragon!', 'ts': '1579196262.012800', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:43 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:43 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196263.012900', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': "I don't get how every LTM from @PlayApex sounds good on paper but is so poorly executed. Do you not play test anything?", 'ts': '1579196263.012900', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:43 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:43 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196263.013000', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'This is a test of WP to Twitter. <https://t.co/nzJYSkNWql> (5514029)', 'ts': '1579196263.013000', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:44 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:44 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196264.013100', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'I’ve been living in my lab for the past few days and I just came up for air to see the latest shit storm that is br… <https://t.co/6c9XgQi0oP>', 'ts': '1579196264.013100', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:45 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:45 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196265.013200', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': 'austria drumfabrik tomorrow, lots of music to test <https://t.co/bdWkFskNLk>', 'ts': '1579196265.013200', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:45 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:45 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196265.013300', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@TS_SCI_MAJIC12 @covertress soetoro is agitating again. he wants trump to get involved with the debate, then they f… <https://t.co/UX3RF1hZQX>', 'ts': '1579196265.013300', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:46 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:46 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:46 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196266.013500', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '@rdalwale @cricketcomau @thetest_amazon @ICC well said bro . Test cricket is a beauty of cricket', 'ts': '1579196266.013500', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:46 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:46 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:47 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7807 - 20-01-16 12:37:47 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7807 - 20-01-16 12:37:47 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7807 - 20-01-16 12:37:47 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7807 - 20-01-16 12:37:47 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7807 - 20-01-16 12:37:47 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7807 - 20-01-16 12:37:47 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7807 - 20-01-16 12:37:47 - ERROR -  Slack - Unhandled Exception: This event loop is already running
Traceback (most recent call last):
  File "/media/jt/JT's SSHD/Kenzie/quarter3/backend-slacktweet/slack_client.py", line 132, in private_message_jt
    text=text
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/jt/.local/share/virtualenvs/backend-slacktweet-8puf694V/lib/python3.7/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
7807 - 20-01-16 12:37:47 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:47 - DEBUG - Received the following response: {'ok': True, 'channel': 'DSD690213', 'ts': '1579196267.013800', 'message': {'type': 'message', 'subtype': 'bot_message', 'text': '#IMPOTUS45 #FamiliesBelongTogether #VoteBlueNoMatterWho #climatestrike #LGBTQIA #Trans #POC #Democrats #Christians… <https://t.co/37KuaDiJc5>', 'ts': '1579196267.013800', 'username': 'Best-Slack-Bot', 'bot_id': 'BS0CA5N3U'}}
7807 - 20-01-16 12:37:47 - DEBUG - Running 1 callbacks for event: 'message'
7807 - 20-01-16 12:37:47 - INFO - DSD690213
7807 - 20-01-16 12:37:47 - DEBUG - Updating twitter filter keywords
7807 - 20-01-16 12:37:47 - DEBUG - Restarting the twitter stream
7807 - 20-01-16 12:37:47 - DEBUG - Disoconnecting Stream
7807 - 20-01-16 12:37:47 - DEBUG - Starting Twitter Stream
